### ISSUE TITLE
How to implement `exactly_one_of` validation?

### ISSUE THREAD

**Issue by maxd** [dryrb/dry-validation#25]
Could you please explain how to implement [exactly_one_of](https://github.com/ruby-grape/grape#exactly_one_of) validation?

Is it possible to implement such validation with `rule` predicate?

**Comment by solnic** [comment]
not supported, yet. but I plan to do something like this:

``` ruby
optional(:beer)
optional(:wine)

 # exactly one of
rule(:beer, :wine) { |beer, wine|  beer.filled? ^ wine.filled? }

 # at least one of
rule(:beer, :wine) { |beer, wine|  beer.filled? | wine.filled? }

 # all or none
rule(:beer, :wine) { |beer, wine|  beer.filled? & wine.filled? }
```

**Comment by solnic** [comment]
The final interface is slightly different from what I showed in the previous comment. Please see the [wiki](https://github.com/dryrb/dry-validation/wiki/High-level-Rules#rules-depending-on-results-from-other-rules) for more information.
