### ISSUE TITLE
dry-validation doesn't recognize integer in string

### ISSUE THREAD

**Issue by maxd** [dryrb/dry-validation#26]
README has the following example:

```
key(:age) { |value| value.int? & value.gt?(18) }
...
errors = schema.call('email' => '', 'age' => '18').messages
...
#   :age => [["age must be greater than 18 (18 was given)", 18]]
...
```

As you can see `18` declared as string value but validation recognize it as integer value and validate it. Seems like this is don't work now (don't recognize integer value in string and raise error: `age must be an integer`). 

Is it bug in validation or README?

**Comment by solnic** [comment]
`Schema::Form` tries to coerce values based on type expectations, so it does coercions prior validation.
