### ISSUE TITLE
Seems like `size?(range)` doesn't work

### ISSUE THREAD

**Issue by maxd** [dryrb/dry-validation#27]
I have the following validator:

```
key(:region_iso_code) { |v| v.str? && v.size?(1..3) }
```

it raise the following error:

```
{:region_iso_code=>[["region_iso_code length must be within 1 - 3", "MOS"]]}
```

As you can see the input value `MOS` doesn't pass validation. Is it bug?

**Comment by solnic** [comment]
It's a bug in the form of a missing feature that I thought was done :joy: looks like `size?` predicate doesn't really support ranges. I'll fix it tomorrow and push 0.3.1 :)

**Comment by maxd** [comment]
Checked. All works fine. Thank you! :+1:

**Comment by solnic** [comment]
@maxd ah thanks for testing it :) I'll push 0.3.1 later today
