### ISSUE TITLE
Lots of RuboCop offenses

### ISSUE THREAD

**Issue by zacholauson** [dryrb/dry-validation#33]
I would be happy to help either disable some of the active RuboCop inspections, or change the code to follow the default inspections.

Do you guys have any preference on how to solve all of these?

**Comment by solnic** [comment]
Hey, yes I'd accept a PR that fixes the issues with the exception of `.()` calls, I love it and I want to make it more popular, esp. that you can attach some extra meaning to it, ie. such calls could mean a side-effect-less call that is functional. I hope @AMHOL can get used to it? :joy:

**Comment by zacholauson** [comment]
Awesome. I like the `.()` call syntax as well. I haven't seen it used very much so its cool to see it used so consistently in this project.

I'll start working through the offenses and post back if I have any questions about desired code style.

Thanks!

**Comment by zacholauson** [comment]
@solnic, I opened a work in progress pull request as I work through the offenses. Initially I disabled the inspection that prefers `.call()` over `.()`, but we could also change this inspection to enforce `.()` over  `.call()`. What would you prefer?

**Comment by solnic** [comment]
I'd say we should simply disable this check

**Comment by zacholauson** [comment]
Sounds good. Thanks @solnic

**Comment by AMHOL** [comment]
@solnic @zacholauson I can live with it lol

**Comment by zacholauson** [comment]
Hey guys, just as an update. I've been home visiting family so I haven't been working on this much. I plan to continue to work on it this weekend, I have about 10 offenses left.

**Comment by solnic** [comment]
No worries man :) BTW a lot of code has been moved to [dry-logic](https://github.com/dryrb/dry-logic).
