### ISSUE TITLE
How I can get index of element with errors in array

### ISSUE THREAD

**Issue by badenkov** [dryrb/dry-validation#36]
Hello!

In your example of validation elements in array we can't get index of element in array where is error.
How I can get index?

```
class Schema < Dry::Validation::Schema
  key(:phone_numbers) do |phone_numbers|
    phone_numbers.array? do
      phone_numbers.each(&:str?)
    end
  end
end

schema = Schema.new
errors = schema.call(phone_numbers: ['123456789', 123456789]).messages
puts errors.inspect
# {
#   :phone_numbers => [
#     {
#       :phone_numbers => [
#         ["phone_numbers must be a string", 123456789]  << Error in element with index 1
#       ]
#     }
#   ]
# }
```

**Comment by solnic** [comment]
There's a planned feature to support ease access to this information (I know it's useful!), so I'm gonna mark this as a feature request.

**Comment by solnic** [comment]
Oh I should probably mention that for the time being you can already access entire value for the `each` rule via `result = schema.call(input); result.failures`. From there you can find the failure for a given rule and look at its input which includes all phone numbers and just do `input.index(number_that_failed)`. Hope this helps for now :)

**Comment by badenkov** [comment]
Thank you

**Comment by solnic** [comment]
@badenkov there was an issue with error messages hash structure, I just fixed it in master so you now have all info inside that hash, ie:

```
{:phone_numbers=>[[{:phone_numbers=>[["phone_numbers must be a string"], 123456789]}], ["123456789", 123456789]]}
```

So, as you can see, you have access to messages for a specific value and the whole collection from which that value comes from.
