### ISSUE TITLE
Expose AST for schema before call 

### ISSUE THREAD

**Issue by timriley** [dryrb/dry-validation#38]
I'd like to provide validation support for the form builder gem that I'm developing. It's easy enough just to run the form's data through a dry-validation schema after it's been posted, but that's only half of the story. The other half is providing the form builder's UI layer with information about any validation rules _before_ they've been applied – this would allow it to display validation hints as well as perform some simple validations client-side with JS.

I know you've mentioned the idea of "validation hints" before, @solnic, and I'm guessing this is somewhat related. Do you think it might be worthwhile exposing some AST of the validation schema _before_ it's been called with data? Then we could write an AST compiler that associates validation rule info along with each of the fields we display in our forms.

I'd be happy to have a go at exposing the AST as a first step, if you think this is a reasonable feature to support.

**Comment by solnic** [comment]
You have access to rule AST via `YourSchema.rules`. We need to see how we could use that for hints, it should be enough as all the relevant info is there. I was planning to add a "hint compiler" that would use this AST to produce hints.

**Comment by timriley** [comment]
Ah, thanks for pointing me towards `.rules`! I didn't realise it existed :)

**Comment by solnic** [comment]
Right, actually I forgot that it's an AST wrapped in DSL objects, so you gotta do `rules.map(&:to_ary)` to get a pure AST

**Comment by solnic** [comment]
I added support for `hints`. Is there anything special you need in order to implement your form builder?

**Comment by timriley** [comment]
The AST is pretty much all we should need, I think, but the hints will hopefully make it even nicer :)

Feel free to close this on, I reckon, and I can raise smaller things separately if I come across any other issues when we get to integrating the validation. 

Thanks :)

**Comment by solnic** [comment]
Roger that

**Comment by kurko** [comment]
FYI I needed to get just the keys (incl. nesting) to shove into strong_parameters, so I write this for whoever needs this in the future:

```rb
    def self.creative_keys_ast
      [ast_predicate(MySchema)]
    end

    # Recursive algorithm to fetch dry-validation schema's keys
    def self.ast_keys(rule, ast = [])
      if rule.respond_to?(:rules)
        rule.rules.map(&:to_ary).each do |node_rule|
          subtree = ast_keys(node_rule[1].rules[1].rules[1].rules[0])
          if subtree.blank?
            ast << node_rule[0]
          else
            ast << {
              node_rule[0] => subtree
            }
          end
        end
      end

      ast.flatten
    end
```

I had to figure out how to get those rules arrays used. It looks pretty messy.
