### ISSUE TITLE
Add ability to define your own predicates

### ISSUE THREAD

**Issue by solnic** [dryrb/dry-validation#4]
Right now only `Validation::Predicates` module is the container for built-in predicates but we need a way to define our own predicates too and use them in the schema objects.

**Comment by AMHOL** [comment]
We could use `Dry::Container.import` with a `Dry::Container::Namespace` with a `nil` name (global namespace)?

**Comment by solnic** [comment]
That's what crossed my mind, I just didn't know how to do it :) What would be nice is doing `extend Dry::Validation::Predicates` (or include?) and have the interfaces for defining predicates available *and* access to the built-in predicates.

**Comment by timriley** [comment]
Incidentally, this sort of thing would work well for a multiple sub-apps Rodakase setup (a top level container with shared things that each sub-app's container would extend).

**Comment by solnic** [comment]
this is done
