### ISSUE TITLE
Error messages for groups (like the "confirmation" short-cut) can't be generated

### ISSUE THREAD

**Issue by timriley** [dryrb/dry-validation#47]
If I have a schema like this:

```ruby
class MySchema < Dry::Validation::Schema
  confirmation(:password)  
end
```

And call it with invalid confirmation data:

```
v = MySchema.new.call(password: "foo", password_confirmation: "bar")
```

Then it looks like it's not possible to provide YML or i18n data to provide a human-friendly error message for that validation failure.

The reason for this is that the error AST entry for that failure has a `:group` in it:

```ruby
pry(main)> v.errors.map(&:to_ary)
# => [[:error, [:input, [:password_confirmation, ["foo", "bar"], [[:group, [:password_confirmation, [:predicate, [:eql?, []]]]]]]]]]
```

And the `ErrorCompiler` has no `#visit_group` method, which means it goes through to `#method_missing` and just returns `{value: args[1]}` output for the validation result's `#messages`, i.e.

```ruby
pry(main)> v.messages
# => {:password_confirmation=>[[{:value=>:password_confirmation}], ["foo", "bar"]]}
```

Because it goes through `#method_missing` in the error compiler, it means it never actually tries to look up an i18n/yml key for the translated error message for that validation failure.

Is my understanding of this correct? Is this just a matter of updating the `ErrorCompiler` to support groups? Or have I missed some already existing way to actually provide human-friendly error messages for failures like this?

Thanks :)

**Comment by solnic** [comment]
I never added support for grouped rules to the error compiler, so yes, this is a missing feature.

**Comment by timriley** [comment]
Cool, thanks for confirming. I can try take a stab at this, if you like (though it might have to be across the next couple of weeks). Is there anything you'd like to see here, for example around the names of the lookup keys for the messages?

**Comment by solnic** [comment]
@timriley I'm gonna do it tomorrow, it's more involved than I thought and I'm already working in this area with other improvements
