### ISSUE TITLE
Possible performance issue

### ISSUE THREAD

**Issue by gogainda** [dryrb/dry-validation#52]
On [this](https://github.com/dryrb/dry-validation/blob/250f7a41478e7b17530c3a2be4d605f89928c60c/lib/dry/validation/schema/definition.rb#L29) line  was used .any? method which is slow especially when used with big lists. More info and measures could be found [here](https://github.com/dryrb/dry-validation/blob/250f7a41478e7b17530c3a2be4d605f89928c60c/lib/dry/validation/schema/definition.rb#L29)

**Comment by solnic** [comment]
Thanks for pointing this out, you're right. I'll be fine-tuning things at some point in the near future.

**Comment by gogainda** [comment]
I found this tool useful, try it https://github.com/DamirSvrtan/fasterer

**Comment by backus** [comment]
> I found this tool useful, try it https://github.com/DamirSvrtan/fasterer

If you add rubocop to the build too the latest version has a lot of performance cops that might help

**Comment by solnic** [comment]
ugh, looks like I referenced incorrect issue in these commits...anyhow, thanks for suggestions, I'm familiar with fasterer. Rubocop is being used on codeclimate, it's nicer to have it there.

**Comment by solnic** [comment]
This line is gone, so I'm gonna close this one :)
