### ISSUE TITLE
Rules AST no longer includes "set" elements for nested keys

### ISSUE THREAD

**Issue by timriley** [dryrb/dry-validation#58]
Firstly, as you know, I'm a big fan :) And I'm looking to make [formalist](https://github.com/icelab/formalist) integrate more closely with dry-validation right now.

In formalist, we work with the dry-validation rules AST in order to incorporate schema rule information into our form elements (with the idea being that front-end form renderers can include matching client-side validation or hint text).

For schemas with nested keys, we rely on a `:set` element being present so we can look for that and use it as a why to go deeper into the nested keys. However, it seems like these `:set` elements have disappeared with your work since 0.6.0.

For example, with this little example:

```ruby
class OneLevelSchema < Dry::Validation::Schema
  key(:outer) { |outer|
    outer.key(:inner, &:filled?)
  }
end

one = OneLevelSchema.new
pp one.rules.map(&:to_ary)
```

On 0.6.0, we see this output:

```ruby
[[:and,
  [[:key, [:outer, [:predicate, [:key?, [:outer]]]]],
   [:set,
    [:outer,
     [[:and,
       [[:key, [:inner, [:predicate, [:key?, [:inner]]]]],
        [:val, [:inner, [:predicate, [:filled?, []]]]]]]]]]]]]
```

But on `master`, we see this:

```ruby
[[:and,
  [[:key, [:outer, [:predicate, [:key?, [:outer]]]]],
   [:and,
    [[:key, [:inner, [:predicate, [:key?, [:inner]]]]],
     [:val, [:inner, [:predicate, [:filled?, []]]]]]]]]]
```

Is this a regression/bug, or is the removal of the `:set` element here intentional?

**Comment by solnic** [comment]
It was intentional but obviously it was a mistake. Thanks for reporting
this, I will restore previous behavior.

**Comment by timriley** [comment]
Thanks @solnic! :)

**Comment by solnic** [comment]
Hey @timriley - I haven't changed this after all. If a given key has only one rule associated with it, then `:set` is not needed. I *think* formalist should be able to figure things out nevertheless. I'm gonna look into updating formalist to work with the new ast and see if I'm right.
