### ISSUE TITLE
Add new predicates

### ISSUE THREAD

**Issue by solnic** [dryrb/dry-validation#6]
We just have 8 basic predicates that I wrote pretty much only for testing purposes, but obviously we need a ton more to cover common functionality, like (from the top of my head):

- [x] `size?(num)` - matches exact size
- [x] `format?(regex)` - matches a string against a regexp
- [x] `inclusion?(list)` - checks if a given value is included in the provided list (although I should say this feels too low level and typically I'd probably prefer a custom predicate that would re-use this one)
- [x] `lt?(num)`- matches if a given input is less than the specified one
- [x] `lte?(num)` - matches if a given input is less than or equal to the specified one
- [x] `gte?(num)` - self-explanatory
- [x] `eql?(anything)` - matches exact equality
- [x] `within?(range)` - matches if the input is within the given range

I'm inclined to provide higher-level predicates too, like `email?` etc.

Please tell me if something is missing :)

**Comment by kwando** [comment]
```gt```

**Comment by solnic** [comment]
@kwando it's there already, I should've mentioned where the ones we have are [located](https://github.com/dryrb/dry-validation/blob/master/lib/dry/validation/predicates.rb)

**Comment by AMHOL** [comment]
@kwando `gt?` is already there, @solnic started adding some of these, was going with `lteq?` and `gteq?`, WDYT?

**Comment by solnic** [comment]
`lte` or `lteq`? not sure which one is better

**Comment by kwando** [comment]
I vote for ```lte```

**Comment by solnic** [comment]
I'm wondering now, since we have `lte?` then maybe we should also have `3g?`, `gprs?` and `edge?`, just for backward compatibility. What do you think? :joy:

**Comment by AMHOL** [comment]
Assuming we will have an `eq?` predicate I'd be inclined to go with `lteq?` and `gteq?`. WRT email validations and such, I'd probably leave that out of the core gem, people may want to validate format, or actually check mx records and stuff

**Comment by kwando** [comment]
What about ```:less_than_or_equal_to?``` :trollface: 

I think that ```gte?``` and ```lte?``` is more common, though I cannot back that claim up in anyway.

Also a predicate for ```url?``` would be awesome.
 
@AMHOL seems like a sound idea to make the complex predicates opt-in.
@solnic +1 for backwards compatibility :joy:

**Comment by kwando** [comment]
Length validations, for strings etc. "Username needs to be at least 4 characters long".

**Comment by solnic** [comment]
@kwando can't we use `size` and `min_size` and `max_size` for strings too?

**Comment by kwando** [comment]
@solnic yeah ofc.. once more I failed to look at your code, sorry.

What about passing a range to size? ?

**Comment by solnic** [comment]
@kwando that could work, we only need (in general) some pattern-patching thingie when compiling errors into messages, because you want a diff error message based not just on the predicate identifier, but also on its arguments and input value. ie `size?(6, "string")` vs `size?(1..4, [1,2])` will have to be matched based on `size?` + `6` + `"string"` etc.

Makes sense?

**Comment by AMHOL** [comment]
Didn't add `within?` but that's covered by `inclusion?`

**Comment by solnic** [comment]
Thinking about a different word for `inclusion?`, maybe `one_of?(%w(foo bar))` would be better?

**Comment by AMHOL** [comment]
I prefer inclusion TBH, only other word I can think of is contains, not sure how to negate that with something that flows nicely though

**Comment by kwando** [comment]
How about in? ?

**Comment by solnic** [comment]
@kwando so `in?` and `not_in?` this is nice, I think. WDYT @AMHOL?

**Comment by AMHOL** [comment]
Yeah, that works

**Comment by aptinio** [comment]
How about using the built-in predicates or matching them somehow?
* `is_a?(String)` and `kind_of?(Fixnum)` instead of `str?` and `int?`
* `matches?(regex) for Regexp#.match(str)
* `included_in?(array) for `Array#include?(obj)`
* `member_of?(range) for `Range#member?(obj)`
* `covered_by?(range) for `Range#cover?(obj)`

**Comment by aptinio** [comment]
Also, can we use `:<`, `:>`, `:<=`, etc. instead of `:lt?`, `:gt?`, `:lteq?`, etc? Technically, they won't be predicates anymore though.

**Comment by solnic** [comment]
@aptinio I've been optimizing for conciseness :) we could support `value > 18` etc. too, those are just operators. I'm open to do that and see what people like better.

**Comment by kwando** [comment]
I was thinking about overriding the "operators" too the other day, though I'm unsure about the precedence rules of ```age > 3 & age < 99``` , if one have to write rules like ```(age > 3) & (age < 99)``` then I like ```:gt?(<value>)``` and friends more.

**Comment by aptinio** [comment]
Cool. I'd like to help out with dryrb and rodakase projects whenever I can. I'm all for their projects goals and concepts, and this seems a good place to get my feet wet.

**Comment by solnic** [comment]
I added remaining preciates (`:format?` and `eql?`), thanks @AMHOL for dealing with the others!

I also made it possible to define error message templates based on the predicate argument type, ie `size?` already supports this:

``` yaml
size?:
  range: "%{name} size must be within %{left} - %{right}"
  default: "%{name} size must be %{num}"
```

Which means that if you have a rule `value.size?(1..10)` then the range template will be used for the message.

We can do the same trick with other predicates, when it makes sense. It's *probably* a good idea to do the same thing with the actual input that is validated. Gotta experiment with that more.

I'm gonna close this issue now. Please report new issues if you're missing some predicate and you think it should be built-in.

@aptinio that's awesome to know, thanks! I'll be adding new issues describing some features that I think could be very useful, maybe you'll find something interesting to work on. Of course if you have any ideas how to make this lib (or other dry-* gems) better, please just let me know. I'll be working more on rodakase next week, I'll try to prepare a roadmap for it too by reporting issues with new features and improvements.
