### ISSUE TITLE
Document how to share schema validations

### ISSUE THREAD

**Issue by joevandyk** [dryrb/dry-validation#62]
Say I have Orders and Users to validate, each of which contain an address:

```
{ 
  username: 1,
  address: { 
    street: '123 Main',
    city: 'Seattle'
  }
}

{ 
  product_id: 1,
  address: { 
    street: '123 Main',
    city: 'Seattle'
  }
}
```

it's not clear from the documentation how I could share the address validation between the two schemas.

**Comment by solnic** [comment]
There's no API for it yet, I'll try to add it in the upcoming, big 0.7.0 release, or 0.7.1

**Comment by solnic** [comment]
I'm going to make it possible to simply write `key(:address, AddressSchema)`. Sounds good?

**Comment by timriley** [comment]
Would you expect `AddressSchema` to be a Schema class or instance? Just wondering about how you'd go about composing schemas that need to be instantiated with dependencies provided for their own custom predicate methods to work...

**Comment by solnic** [comment]
@timriley I want to see if it's feasible to always use nested schemas, so that under each key you have a schema object and you can nest them, then schema rules would become a hash of nested schemas

**Comment by solnic** [comment]
immediate update: we can't assume a nested schema when using `key` syntax because it could be either a nested hash or a flat value. So I'm wondering about either `key(:foo, schema: true) { .. }` or `schema(:foo) { .. }`. Hmm
