### ISSUE TITLE
Extending or Inherit schema

### ISSUE THREAD

**Issue by onemanstartup** [dryrb/dry-validation#69]
Is there a way? Ot will it be possible to merge rules or extend? Right now inheritance overwrite all rules.

**Comment by solnic** [comment]
I'll make sure it'll work in next version

**Comment by solnic** [comment]
In 0.7.0 the way you define schemas will change, it's no longer going to be a class definition, a custom API will be provided that will look more or less like that:

``` ruby
```

**Comment by waiting-for-dev** [comment]
Hey, just out of curiosity, is there any solid reason to use this custom API? On the surface it looks like a quite arbitrary violation of the principle of least surprise. Thanks!

**Comment by solnic** [comment]
@waiting-for-dev yes there is, the builder methods allow you to define rules with 1-level of indentation less and can build a schema object for you, or generate a class with static configuration. Initially it was part of the `Schema` class but it added additional complexity that I didn't like to maintain. Inheritance here is a bit tricky, we store rules separately in configuration, you can inherit rules but it doesn't mean you want to inherit coercion logic too, so things must be kept separated and there needs to be a little bit of additional orchestration, hence we've got custom API for building schema objects. You can totally define a class too and we could easily expose a DSL for rules on the class level (like hanami-validations) but the downside is that people would have to remember that they want to memoize schema instances. Initially I was doing `SomeSchema = Class.new(Schema) { .. }.new` and that was just plain ugly, so I added these builder methods.

**Comment by waiting-for-dev** [comment]
Thanks for the reply. Now it makes sense :)

**Comment by shagabutdinov** [comment]
Is there a way to extend several schemas? Like this:

```
Dry::Validation.Schema(OtherSchema1, OtherSchema2) do
  # your rules
end
```

?

**Comment by alexandru-calinoiu** [comment]
Is there a way to do this with 1.0?

**Comment by solnic** [comment]
@alexandru-calinoiu wdym by `this`?
